name: Build Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            output_name: 不動産スクレイパー.exe
            artifact_name: Windows
          - os: macos-latest
            output_name: 不動産スクレイパー
            artifact_name: macOS
          - os: ubuntu-latest
            output_name: 不動産スクレイパー
            artifact_name: Linux
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests beautifulsoup4 pandas
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "不動産スクレイパーv2" scraper_gui_v2.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/*
        retention-days: 30

